#!/usr/bin/env bash
set -euo pipefail

# ---------------------------------------------------------------------------
# tools/yubi_lid_setup.sh
#
# Prevent suspend when the laptop lid is closed (useful when running the
# bringup on a laptop that needs to keep recording while the lid is shut).
# Subcommands: apply / reset / status.
# See `--help` for full usage.
#
# Implementation note: we install a systemd-logind drop-in under
# /etc/systemd/logind.conf.d/ instead of editing /etc/systemd/logind.conf,
# so `remove` is a clean unlink and the distro's main config stays pristine.
# ---------------------------------------------------------------------------

DROPIN_DIR="/etc/systemd/logind.conf.d"
DROPIN_FILE="${DROPIN_DIR}/99-yubi-lid.conf"
SERVICE_NAME="systemd-logind"

usage() {
  cat <<'USAGE'
Usage:
  sudo ./tools/yubi_lid_setup.sh apply
  sudo ./tools/yubi_lid_setup.sh reset
  ./tools/yubi_lid_setup.sh status
  ./tools/yubi_lid_setup.sh -h | --help

Subcommands:
  apply    Install a systemd-logind drop-in that sets
             HandleLidSwitch=ignore
             HandleLidSwitchExternalPower=ignore
             HandleLidSwitchDocked=ignore
           and restart systemd-logind so the policy takes effect
           immediately. Closing the lid will no longer suspend the PC.
  reset    Delete the drop-in and restart systemd-logind so the distro
           default lid behavior (usually suspend) is restored.
  status   Show whether the drop-in is installed and what systemd-logind
           currently reports for the three Handle* properties.

Notes:
  - This script does NOT modify /etc/systemd/logind.conf. The drop-in at
    ${DROPIN_FILE} overrides only the three lid-switch keys; everything
    else in the main config is unaffected.
  - 'apply' is idempotent: re-running it just rewrites the drop-in.
USAGE
}

# --- helpers ---------------------------------------------------------------

require() {
  command -v "$1" >/dev/null 2>&1 \
    || { echo "ERROR: missing command: $1" >&2; exit 2; }
}

ensure_root() {
  if [[ $EUID -ne 0 ]]; then
    echo "ERROR: this subcommand requires root. Re-run with sudo." >&2
    exit 1
  fi
}

# --- subcommands -----------------------------------------------------------

cmd_apply() {
  ensure_root
  require systemctl

  mkdir -p "$DROPIN_DIR"
  cat > "$DROPIN_FILE" <<EOF
# Auto-generated by tools/yubi_lid_setup.sh on $(date --iso-8601=seconds)
# Override systemd-logind so closing the laptop lid does NOT suspend the PC.
# Managed file -- safe to remove via: sudo ./tools/yubi_lid_setup.sh reset
[Login]
HandleLidSwitch=ignore
HandleLidSwitchExternalPower=ignore
HandleLidSwitchDocked=ignore
EOF
  chmod 644 "$DROPIN_FILE"
  echo "Wrote: $DROPIN_FILE"

  echo "Restarting ${SERVICE_NAME}..."
  if ! systemctl restart "${SERVICE_NAME}.service"; then
    echo "ERROR: ${SERVICE_NAME} failed to restart. Recent logs:" >&2
    journalctl -u "${SERVICE_NAME}.service" -n 50 --no-pager >&2 || true
    exit 1
  fi

  echo
  echo "=== Summary ==="
  echo "Drop-in installed: ${DROPIN_FILE}"
  show_logind_props
  echo "Done. Closing the lid will no longer suspend the PC."
}

cmd_reset() {
  ensure_root
  require systemctl

  if [[ -f "$DROPIN_FILE" ]]; then
    rm -f "$DROPIN_FILE"
    echo "Removed: $DROPIN_FILE"
  else
    echo "(skip) ${DROPIN_FILE} not present."
  fi

  # Clean up the directory if we created it and it's now empty -- avoids
  # leaving behind a stray empty conf.d that confuses future audits.
  if [[ -d "$DROPIN_DIR" ]] && [[ -z "$(ls -A "$DROPIN_DIR" 2>/dev/null)" ]]; then
    rmdir "$DROPIN_DIR" 2>/dev/null || true
  fi

  echo "Restarting ${SERVICE_NAME}..."
  if ! systemctl restart "${SERVICE_NAME}.service"; then
    echo "ERROR: ${SERVICE_NAME} failed to restart. Recent logs:" >&2
    journalctl -u "${SERVICE_NAME}.service" -n 50 --no-pager >&2 || true
    exit 1
  fi

  echo
  echo "=== Summary ==="
  echo "Drop-in removed. Distro default lid behavior restored."
  show_logind_props
  echo "Done."
}

show_logind_props() {
  if ! command -v busctl >/dev/null 2>&1; then
    return 0
  fi
  echo "systemd-logind reports:"
  for prop in HandleLidSwitch HandleLidSwitchExternalPower HandleLidSwitchDocked; do
    # busctl prints `s "value"` -- extract the quoted body. An empty value
    # ("") means systemd inherits from HandleLidSwitch, which we annotate
    # rather than showing a misleading <unknown>.
    local raw val
    raw="$(busctl get-property org.freedesktop.login1 /org/freedesktop/login1 \
            org.freedesktop.login1.Manager "$prop" 2>/dev/null || true)"
    if [[ -z "$raw" ]]; then
      val="<unavailable>"
    else
      val="$(printf '%s\n' "$raw" | cut -d'"' -f2)"
      if [[ -z "$val" ]]; then
        val="(inherits HandleLidSwitch)"
      fi
    fi
    printf '  %-32s = %s\n' "$prop" "$val"
  done
}

cmd_status() {
  if [[ -f "$DROPIN_FILE" ]]; then
    echo "Drop-in present: ${DROPIN_FILE}"
    echo "--- contents ---"
    cat "$DROPIN_FILE"
    echo "----------------"
  else
    echo "Drop-in NOT present: ${DROPIN_FILE}"
  fi
  echo
  show_logind_props
}

# --- dispatch --------------------------------------------------------------

if [[ $# -eq 0 ]]; then
  usage
  exit 2
fi

SUBCMD="$1"
shift || true

case "$SUBCMD" in
  -h|--help) usage; exit 0 ;;
  apply)     cmd_apply  "$@" ;;
  reset)     cmd_reset  "$@" ;;
  status)    cmd_status "$@" ;;
  *)
    echo "ERROR: unknown subcommand: $SUBCMD" >&2
    echo >&2
    usage >&2
    exit 2
    ;;
esac
